/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Chat example
 * The chat API description
 * OpenAPI spec version: 1.0
 */
import { createInstance } from './api-instace';
import type { BodyType } from './api-instace';
export type AuthControllerGoogleAuthParams = {
    token: string;
};

export type AuthControllerRefreshTokensParams = {
    refreshToken: string;
};

export type AuthControllerLogoutParams = {
    refreshToken: string;
};

export interface Tokens {
    [key: string]: any;
}

export interface ResponseUserWithTokens {
    accessToken: string;
    createdAt: string;
    email: string;
    id: number;
    image: string;
    name: string;
    refreshToken: string;
}

export interface LoginDto {
    email: string;
    password: string;
}

export interface RegisterDto {
    email: string;
    password: string;
    passwordRepeat: string;
}

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const usersControllerFindById = (
    id: number,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<void>(
        { url: `/api/users/find/by-id/${id}`, method: 'GET' },
        options,
    );
};

export const usersControllerFindByEmail = (
    email: string,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<void>(
        { url: `/api/users/find/by-email/${email}`, method: 'GET' },
        options,
    );
};

export const usersControllerMe = (
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<void>(
        { url: `/api/users/me`, method: 'GET' },
        options,
    );
};

export const usersControllerRemove = (
    id: number,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<void>(
        { url: `/api/users/${id}`, method: 'DELETE' },
        options,
    );
};

export const authControllerCredentialsRegister = (
    registerDto: BodyType<RegisterDto>,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<void>(
        {
            url: `/api/auth/credentials/register`,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            data: registerDto,
        },
        options,
    );
};

export const authControllerCredentialsLogin = (
    loginDto: BodyType<LoginDto>,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<ResponseUserWithTokens>(
        {
            url: `/api/auth/credentials/login`,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            data: loginDto,
        },
        options,
    );
};

export const authControllerLogout = (
    params: AuthControllerLogoutParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<void>(
        { url: `/api/auth/logout`, method: 'GET', params },
        options,
    );
};

export const authControllerRefreshTokens = (
    params: AuthControllerRefreshTokensParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<Tokens>(
        { url: `/api/auth/refresh-tokens`, method: 'GET', params },
        options,
    );
};

export const authControllerGoogleAuth = (
    params: AuthControllerGoogleAuthParams,
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<ResponseUserWithTokens>(
        { url: `/api/auth/google`, method: 'GET', params },
        options,
    );
};

export const attachmentsControllerUploadFile = (
    options?: SecondParameter<typeof createInstance>,
) => {
    return createInstance<void>(
        { url: `/api/attachments/upload/image`, method: 'POST' },
        options,
    );
};

export type UsersControllerFindByIdResult = NonNullable<
    Awaited<ReturnType<typeof usersControllerFindById>>
>;
export type UsersControllerFindByEmailResult = NonNullable<
    Awaited<ReturnType<typeof usersControllerFindByEmail>>
>;
export type UsersControllerMeResult = NonNullable<
    Awaited<ReturnType<typeof usersControllerMe>>
>;
export type UsersControllerRemoveResult = NonNullable<
    Awaited<ReturnType<typeof usersControllerRemove>>
>;
export type AuthControllerCredentialsRegisterResult = NonNullable<
    Awaited<ReturnType<typeof authControllerCredentialsRegister>>
>;
export type AuthControllerCredentialsLoginResult = NonNullable<
    Awaited<ReturnType<typeof authControllerCredentialsLogin>>
>;
export type AuthControllerLogoutResult = NonNullable<
    Awaited<ReturnType<typeof authControllerLogout>>
>;
export type AuthControllerRefreshTokensResult = NonNullable<
    Awaited<ReturnType<typeof authControllerRefreshTokens>>
>;
export type AuthControllerGoogleAuthResult = NonNullable<
    Awaited<ReturnType<typeof authControllerGoogleAuth>>
>;
export type AttachmentsControllerUploadFileResult = NonNullable<
    Awaited<ReturnType<typeof attachmentsControllerUploadFile>>
>;
