openapi: 3.0.0
paths:
  /api/users/find/by-id/{id}:
    get:
      operationId: UsersController_findById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
  /api/users/find/by-email/{email}:
    get:
      operationId: UsersController_findByEmail
      parameters:
        - name: email
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /api/users/me:
    get:
      operationId: UsersController_me
      parameters: []
      responses:
        '200':
          description: ''
  /api/users/{id}:
    delete:
      operationId: UsersController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
  /api/auth/credentials/register:
    post:
      operationId: AuthController_CredentialsRegister
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        '201':
          description: ''
  /api/auth/credentials/login:
    post:
      operationId: AuthController_credentialsLogin
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUserWithTokens'
  /api/auth/logout:
    get:
      operationId: AuthController_logout
      parameters:
        - name: refreshToken
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
  /api/auth/refresh-tokens:
    get:
      operationId: AuthController_refreshTokens
      parameters:
        - name: refreshToken
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /api/auth/google:
    get:
      operationId: AuthController_GoogleAuth
      parameters:
        - name: token
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUserWithTokens'
  /api/attachments/upload/image:
    post:
      operationId: AttachmentsController_uploadFile
      parameters: []
      responses:
        '201':
          description: ''
info:
  title: Chat example
  description: The chat API description
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    RegisterDto:
      type: object
      properties:
        email:
          type: string
          example: ikozluk160@gmail.com
        password:
          type: string
          example: '12345'
        passwordRepeat:
          type: string
          example: '12345'
      required:
        - email
        - password
        - passwordRepeat
    LoginDto:
      type: object
      properties:
        email:
          type: string
          example: ikozluk160@gmail.com
        password:
          type: string
          example: '12345'
      required:
        - email
        - password
    ResponseUserWithTokens:
      type: object
      properties:
        id:
          type: number
        createdAt:
          format: date-time
          type: string
        email:
          type: string
        image:
          type: string
        name:
          type: string
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - id
        - createdAt
        - email
        - image
        - name
        - accessToken
        - refreshToken
    Tokens:
      type: object
      properties: {}
