openapi: 3.0.0
paths:
  /api/users/find/by-id/{id}:
    get:
      operationId: UsersController_findById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - Users
      security:
        - bearer: []
  /api/users/find/by-email/{email}:
    get:
      operationId: UsersController_findByEmail
      parameters:
        - name: email
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Users
      security:
        - bearer: []
  /api/users/me:
    get:
      operationId: UsersController_me
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Users
      security:
        - bearer: []
  /api/users/{id}:
    delete:
      operationId: UsersController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - Users
      security:
        - bearer: []
  /api/users/change-image:
    put:
      operationId: UsersController_changeImage
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Users
      security:
        - bearer: []
  /api/attachments/upload/image:
    post:
      operationId: AttachmentsController_uploadFile
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - Attachments
      security:
        - bearer: []
  /api/attachments:
    get:
      operationId: AttachmentsController_getFileAttachment
      parameters:
        - name: id
          required: true
          in: query
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - Attachments
      security:
        - bearer: []
  /api/messages:
    delete:
      operationId: MessagesController_deleteMessage
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - Messages
      security:
        - bearer: []
  /api/conversations/private:
    get:
      operationId: ConversationsController_createPrivateConversation
      parameters:
        - name: userId
          required: true
          in: query
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - Conversations
      security:
        - bearer: []
  /api/conversations/group:
    post:
      operationId: ConversationsController_createGroupConversation
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGroupConversationDto'
      responses:
        '201':
          description: ''
      tags:
        - Conversations
      security:
        - bearer: []
  /api/conversations/list:
    get:
      operationId: ConversationsController_conversationList
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationListResponse'
      tags:
        - Conversations
      security:
        - bearer: []
  /api/auth/credentials/register:
    post:
      operationId: AuthController_CredentialsRegister
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        '201':
          description: ''
      tags:
        - Auth
  /api/auth/credentials/login:
    post:
      operationId: AuthController_credentialsLogin
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUserWithTokens'
      tags:
        - Auth
  /api/auth/logout:
    get:
      operationId: AuthController_logout
      parameters:
        - name: refreshToken
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Auth
  /api/auth/refresh-tokens:
    get:
      operationId: AuthController_refreshTokens
      parameters:
        - name: refreshToken
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
      tags:
        - Auth
  /api/auth/google:
    get:
      operationId: AuthController_GoogleAuth
      parameters:
        - name: token
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUserWithTokens'
      tags:
        - Auth
info:
  title: My-chat
  description: ''
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    CreateGroupConversationDto:
      type: object
      properties:
        title:
          type: string
          description: Conversation title
          example: group conversation title
        avatarUrl:
          type: string
          description: avatar url
          example: http://example.com/1
      required:
        - title
        - avatarUrl
    ConversationResponse:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        avatarUrl:
          type: string
        type:
          type: string
        senderName:
          type: string
        message:
          type: string
        time:
          format: date-time
          type: string
        messageCount:
          type: number
        messageType:
          type: string
          enum:
            - STANDALONE_MESSAGE
            - SHARED_MESSAGE
            - ANSWERED_MESSAGE
            - SYSTEM_MESSAGE
          example:
            - STANDALONE_MESSAGE
            - SHARED_MESSAGE
            - ANSWERED_MESSAGE
            - SYSTEM_MESSAGE
      required:
        - id
        - title
        - avatarUrl
        - type
        - senderName
        - message
        - time
        - messageCount
        - messageType
    ConversationListResponse:
      type: object
      properties:
        conversations:
          type: array
          items:
            $ref: '#/components/schemas/ConversationResponse'
      required:
        - conversations
    RegisterDto:
      type: object
      properties:
        email:
          type: string
          example: ikozluk160@gmail.com
        password:
          type: string
          example: '12345'
        passwordRepeat:
          type: string
          example: '12345'
      required:
        - email
        - password
        - passwordRepeat
    LoginDto:
      type: object
      properties:
        email:
          type: string
          example: ikozluk160@gmail.com
        password:
          type: string
          example: '12345'
      required:
        - email
        - password
    ResponseUserWithTokens:
      type: object
      properties:
        id:
          type: number
        createdAt:
          format: date-time
          type: string
        email:
          type: string
        image:
          type: string
        name:
          type: string
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - id
        - createdAt
        - email
        - image
        - name
        - accessToken
        - refreshToken
    Tokens:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - accessToken
        - refreshToken
